/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author kevin
 */
public class frmCreditos extends javax.swing.JFrame {

    /**
     * Creates new form frmCreditos
     */
    public frmCreditos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(16, 9, 2));
        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(239, 232, 232));
        jLabel2.setText("Pablo Perez Llacsa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 30));

        jLabel3.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 232, 232));
        jLabel3.setText("14200105");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(239, 232, 232));
        jLabel4.setText("Renzo_13_6@hotmail.com");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel5.setBackground(new java.awt.Color(16, 9, 2));
        jLabel5.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(239, 232, 232));
        jLabel5.setText("Renzo Orihuela Gomero");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 30));

        jLabel6.setBackground(new java.awt.Color(16, 9, 2));
        jLabel6.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(239, 232, 232));
        jLabel6.setText("Kevin Daniel Mendoza Vásquez");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 220, 30));

        jLabel7.setBackground(new java.awt.Color(16, 9, 2));
        jLabel7.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(239, 232, 232));
        jLabel7.setText("Diego Lopez Torres");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, 30));

        jLabel8.setBackground(new java.awt.Color(16, 9, 2));
        jLabel8.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(239, 232, 232));
        jLabel8.setText("Yunior Oncoy Corsino");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, 30));

        jLabel9.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 224, 224));
        jLabel9.setText("Este trabajo no pudo haber sido completado sin la ayuda de ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 70, -1));

        jLabel10.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(239, 232, 232));
        jLabel10.setText("14200026");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(239, 232, 232));
        jLabel11.setText("14200020");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(239, 232, 232));
        jLabel12.setText("14200169");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(239, 232, 232));
        jLabel13.setText("14200023");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel14.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(239, 232, 232));
        jLabel14.setText("Max_DX14@hotmail.com");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(239, 232, 232));
        jLabel15.setText("Pablo_020196@hotmail.com");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel16.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(239, 232, 232));
        jLabel16.setText("Escorjunnior@gmail.com");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel17.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(239, 232, 232));
        jLabel17.setText("https://www.github.com/kevinlll4/Algoritmica2.git");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel1.setBackground(new java.awt.Color(252, 252, 252));
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GGGGGGG.jpg"))); // NOI18N
        jLabel1.setText("Kevin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();  
        Principal x=new Principal();
x.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
