/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ConexionDB.Conexion;
import Datos.DatosEmpleados;
;
import Formularios.Principal;
import Negocios.ngcLogin;
import java.io.File;
import java.io.IOException;


import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Modelos.Cliente;
import Modelos.Usuarios;
import Modelos.vectorPersonas;

import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class frmLogin extends javax.swing.JFrame {

    
 
    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Droid Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(237, 235, 235));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 90, -1));

        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 209, 80, 30));

        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 209, 90, 30));

        lblUsuario.setFont(new java.awt.Font("Droid Serif", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(234, 229, 229));
        lblUsuario.setText("Usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 135, -1));

        lblContrasenia.setFont(new java.awt.Font("Droid Serif", 1, 14)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(234, 229, 229));
        lblContrasenia.setText("Contraseña");
        getContentPane().add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 135, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GGGGGGG.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    /*if(modo==2){
        
     if(Conexion.conexion()!=null){
        
        System.out.println("COnexion realizada correctamente");
    }
    else{
        System.out.println("COnexion fallada");
    }
    } // TODO add your handling code here:*/
    }//GEN-LAST:event_formWindowOpened

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
     /* char[] contra= txtpassword.getPassword();
      String con=new String(contra);
        if(modo==2){
            
            if( ngcLogin.ConsultarLogin(txtUsuario.getText(),con)){
                
                
                try {
                    sleep(3000);
                } catch (InterruptedException ex) {
                    System.out.println("que pasa");
                    Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
                new Principal().show();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Error contraseña o z");
            }
        }*/
       char[] contra= txtpassword.getPassword();
      String con=new String(contra);
            vectorPersonas us=new vectorPersonas();
            
            Usuarios x=new Usuarios();
            x.setNick(txtUsuario.getText());
            x.setPassword(con);
            try {
                File fil=new File("Usuarios.obj");
                if(!fil.exists()){
                    us.crearArchivoC();
                    us.inicialU(con);
                    
                }
                if(DatosEmpleados.usuariosF(us.recuperarArchivo("Usuarios.obj"), x)){
                 
                    try {
                        sleep(3000);
                    } catch (InterruptedException ex) {
                        
                        Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(rootPane,"Bienvenido "+txtUsuario.getText());
                    dispose();
                    new Principal().show();
                    
                    
                }
                else{
                    
                    JOptionPane.showMessageDialog(rootPane,"No hay usuario registrado");
                }
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        
    }//GEN-LAST:event_btnIngresarActionPerformed
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }
 
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
