/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ConexionDB.Conexion;
import Controladores.Codigo;
import Controladores.Comparar;
import Controladores.limpiar;
import Datos.DatosCliente;
import Negocios.ngcRegistrarCliente;
import Negocios.ngcRegistrarCuenta;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import Modelos.Cliente;
import Modelos.Cuenta;
import Modelos.CuentaAhorros;
import Modelos.CuentaCorriente;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class frmRegistrarCliente extends javax.swing.JFrame {

    int modo;

    /**
     * Creates new form frmRegistrarCliente
     */
    public frmRegistrarCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.modo = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        cmbCuenta = new javax.swing.JComboBox();
        txtContraseña = new javax.swing.JPasswordField();
        lblFecha = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("L M Mono Slant10", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(245, 231, 231));
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));
        lblNombre.getAccessibleContext().setAccessibleParent(this);

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 140, -1));
        txtNombre.getAccessibleContext().setAccessibleParent(this);

        txtEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 140, -1));
        txtEdad.getAccessibleContext().setAccessibleParent(this);

        lblEdad.setFont(new java.awt.Font("L M Mono Slant10", 1, 14)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(245, 231, 231));
        lblEdad.setText("Edad");
        getContentPane().add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 60, -1));
        lblEdad.getAccessibleContext().setAccessibleParent(this);

        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 120, 140, -1));
        txtDireccion.getAccessibleContext().setAccessibleParent(this);

        lblDireccion.setFont(new java.awt.Font("L M Mono Slant10", 1, 14)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(245, 231, 231));
        lblDireccion.setText("Direccion");
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        lblDireccion.getAccessibleContext().setAccessibleParent(this);

        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 160, 140, -1));
        txtFecha.getAccessibleContext().setAccessibleParent(this);

        cmbCuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Corriente", "Ahorros" }));
        cmbCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(cmbCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 200, 140, -1));
        cmbCuenta.getAccessibleContext().setAccessibleParent(this);

        txtContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 150, -1));
        txtContraseña.getAccessibleContext().setAccessibleParent(this);

        lblFecha.setFont(new java.awt.Font("L M Mono Slant10", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(245, 231, 231));
        lblFecha.setText("Fecha");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));
        lblFecha.getAccessibleContext().setAccessibleParent(this);

        lblCuenta.setFont(new java.awt.Font("L M Mono Slant10", 1, 14)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(245, 231, 231));
        lblCuenta.setText("Cuenta");
        getContentPane().add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 60, -1));
        lblCuenta.getAccessibleContext().setAccessibleParent(this);

        lblContraseña.setFont(new java.awt.Font("L M Mono Slant10", 1, 14)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(245, 231, 231));
        lblContraseña.setText("Contraseña");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));
        lblContraseña.getAccessibleContext().setAccessibleParent(this);

        jLabel1.setFont(new java.awt.Font("IncisedBlackWide", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 224, 224));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Clientes");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 220, -1));
        jLabel1.getAccessibleContext().setAccessibleParent(this);

        btnRegistrar.setForeground(new java.awt.Color(88, 41, 41));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 70, 30));
        btnRegistrar.getAccessibleContext().setAccessibleParent(this);

        btnSalir.setForeground(new java.awt.Color(88, 41, 41));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 60, 30));
        btnSalir.getAccessibleContext().setAccessibleParent(this);

        jButton1.setForeground(new java.awt.Color(88, 41, 41));
        jButton1.setText("Regresar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 70, 30));

        jButton2.setForeground(new java.awt.Color(88, 41, 41));
        jButton2.setText("Limpiar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 60, 30));

        jLabel3.setFont(new java.awt.Font("L M Mono Slant10", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 231, 231));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Metodo5.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        String Direccion = txtDireccion.getText();
        int Edad = 0;
        try{
        Edad = Integer.parseInt(txtEdad.getText());
       
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane,"Formato en edad incorrecto");
                   
        }
        if(Edad<=0){
                        JOptionPane.showMessageDialog(rootPane,"La edad no puede ser negativa");
                                
        }
        else{
        String Nombre = txtNombre.getText();
        String Fecha = txtFecha.getText();

        Object e = cmbCuenta.getSelectedItem();
        char[] charC = txtContraseña.getPassword();
        String contra = new String(charC);
        String cuenta = String.valueOf(e);

        if (modo == 2) {
            Connection conexion = null;
            conexion = Conexion.conexion();
            String codN = Codigo.CodNombre(txtNombre.getText(), conexion);
            String codC = Codigo.CodCuenta(txtNombre.getText(), conexion);

            Cliente cliente = new Cliente(Nombre, Edad, Fecha, Direccion, codN);
            Cuenta cta;

            if (cuenta.equals("Corriente")) {

                cta = new CuentaCorriente(codC, codN, contra, 0, cuenta);

            } else {

                cta = new CuentaAhorros(codC, codN, contra, 0, cuenta);

            }

            try {
                if (ngcRegistrarCliente.RegistrarC(cliente) && ngcRegistrarCuenta.RegistrarC(cta)) {
                    JOptionPane.showMessageDialog(rootPane, "Cliente registrado exitosamente");

                }

            } catch (SQLException ex) {
                Logger.getLogger(frmRegistrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

            String codNF=" ";
            try {
                codNF = Codigo.CodigoNombreF(Nombre);
            } catch (IOException ex) {
                Logger.getLogger(frmRegistrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmRegistrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

            Cliente cliente = new Cliente(Nombre, Edad, Direccion, Fecha, codNF);
            String codCF=" ";
            try {
                codCF = Codigo.CodigoCuentaF(Nombre);
            } catch (IOException ex) {
                Logger.getLogger(frmRegistrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmRegistrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Cliente antes registro"+cliente.getFecha() + cliente.getNombre());
            Cuenta cta;

            if (cuenta.equals("Corriente")) {

                cta = new CuentaCorriente(codCF, codNF, contra, 0, cuenta);

            } else {

                cta = new CuentaAhorros(codCF, codNF, contra, 0, cuenta);
            }
            try {
                if ( ngcRegistrarCliente.RegistrarCF(cliente)) {
                    if(ngcRegistrarCuenta.RegistrarCF(cta)){
                    JOptionPane.showMessageDialog(rootPane,"CLiente registrado con exito!");
                    
                    }
                    
                }
                else{
                   JOptionPane.showMessageDialog(rootPane,"Hay un error registrando al cliente");

                }
            } catch (IOException ex) {
                System.out.println(ex.getMessage());

            }

        }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

       System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Principal principal=new Principal();
        principal.show();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbCuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
